world_width = 200
steps_per_second = 5
num_organisms = 10000
starting_energy = 100.0
food_energy = 75.0
reproduction_energy_cost = 100.0
move_action_energy_cost = 0.5
turn_energy_cost = 0.5
food_coverage_divisor = 50
max_organism_age = 500
max_num_neurons = 50
speciation_threshold = 20.0

[seed_genome_config]
num_neurons = 10
num_synapses = 100
vision_distance = 10
hebb_eta_baseline = 0.001
hebb_eta_gain = 0.0
eligibility_decay_lambda = 0.9
synapse_prune_threshold = 0.05
mutation_rate_vision_distance = 0.04
mutation_rate_add_edge = 0.03
mutation_rate_remove_edge = 0.05
mutation_rate_split_edge = 0.02
mutation_rate_inter_bias = 0.2
mutation_rate_inter_update_rate = 0.12
mutation_rate_action_bias = 0.2
mutation_rate_eligibility_decay_lambda = 0.05
mutation_rate_synapse_prune_threshold = 0.05
