world_width = 500
steps_per_second = 5
num_organisms = 5000
food_energy = 20
move_action_energy_cost = 1.0
neuron_metabolism_cost = 0.01
plant_growth_speed = 0.05
food_regrowth_interval = 20
food_fertility_noise_scale = 0.012
food_fertility_exponent = 5.0
food_fertility_floor = 0.001
terrain_noise_scale = 0.01
terrain_threshold = 0.70
speciation_threshold = 20.0

[seed_genome_config]
num_neurons = 20
num_synapses = 50
spatial_prior_sigma = 1.0
vision_distance = 10
starting_energy = 250.0
age_of_maturity = 50
hebb_eta_baseline = 0.001
hebb_eta_gain = 0.01
eligibility_retention = 0.95
synapse_prune_threshold = 0.1
mutation_rate_age_of_maturity = 0.04
mutation_rate_vision_distance = 0.04
mutation_rate_num_synapses = 0.05
mutation_rate_inter_bias = 0.2
mutation_rate_inter_update_rate = 0.12
mutation_rate_action_bias = 0.2
mutation_rate_eligibility_retention = 0.05
mutation_rate_synapse_prune_threshold = 0.05
mutation_rate_neuron_location = 0.2
