world_width = 50
steps_per_second = 5
num_organisms = 200
num_neurons = 2
max_num_neurons = 20
num_synapses = 4
turns_to_starve = 20
mutation_chance = 0.04
mutation_magnitude = 1.0
center_spawn_min_fraction = 0.25
center_spawn_max_fraction = 0.75
